"""Prepare everything needed to run SBC_33 LIC_LOADING PRECHECK against the simulator.

Produces, into <out-root>/run/ :

  SBC_33_PRECHECK_sim.yaml   copy of the real template with niam_sbc_server's ssh
                             endpoint repointed at the local simulator. Nothing
                             else is touched - every when/register/validation is
                             the production one.
  scenario.yaml              simulator rules for the three node-side commands,
                             built from the operator-supplied
                             Signaling_Activity_pre_logs.xml.

`netconfprov --table X --readall` returns only table X, so the scenario serves a
<config> wrapper holding just that table (extracted verbatim), not the whole
687 KB dump - which is also what keeps the workflow's `echo '${base64:...}'`
step inside the shell's argument limit.

    python prep_sbc33_precheck.py <template.yaml> <signaling.xml> <out-root>
"""
import os
import re
import sys

SIM_HOST = "127.0.0.1"
SIM_PORT = "22"
SIM_USER = "sbcadmin"
SIM_PASS = "simulated"

# Tables this workflow reads, and the field the compare script pulls from each.
TABLES = ("CapacityLicenseKey", "FeatureLicenseParameters")


def repoint_template(src, dst):
    """Point only niam_sbc_server's ssh host/port/user/password at the simulator."""
    with open(src, encoding="utf-8", newline="") as fh:
        text = fh.read()
    eol = "\r\n" if "\r\n" in text else "\n"
    lines = [l.rstrip("\r") for l in text.split("\n")]

    start = next(i for i, l in enumerate(lines) if l.strip() == "niam_sbc_server:")
    end = next((i for i in range(start + 1, len(lines))
                if re.match(r"^  \S", lines[i])), len(lines))

    changes = []
    for i in range(start, end):
        for key, val in (("host", SIM_HOST), ("port", SIM_PORT),
                         ("user", SIM_USER), ("password", SIM_PASS)):
            m = re.match(r"^(\s+)%s:\s*(.+?)\s*$" % key, lines[i])
            # `user:` also appears nowhere else in this block; `password:` is nested
            if m and key in ("host", "port", "user", "password"):
                old = m.group(2)
                lines[i] = '%s%s: "%s"' % (m.group(1), key, val)
                changes.append("  niam_sbc_server.%s: %s -> %s" % (key, old, val))
                break
    with open(dst, "w", encoding="utf-8", newline="") as fh:
        fh.write(eol.join(lines))
    return changes


def extract_table(xml_text, table):
    m = re.search(r"<{0}\b.*?</{0}>".format(re.escape(table)), xml_text, re.S)
    if not m:
        raise SystemExit("table <%s> not found in the signaling XML" % table)
    return m.group(0)


def build_scenario(xml_text, dst):
    header = re.search(r"<config\b[^>]*>", xml_text)
    if not header:
        raise SystemExit("no <config ...> root element in the signaling XML")
    cfg_open = header.group(0)

    def block(table):
        body = extract_table(xml_text, table)
        body = "\n".join("  " + l if l.strip() else l for l in body.split("\n"))
        return "%s\n%s\n</config>" % (cfg_open, body)

    def indent(text, pad="      "):
        return "\n".join(pad + l for l in text.split("\n"))

    rules = []
    # 1) timestamp used in every generated filename
    rules.append("""  - match: '^date \\+%Y-%m-%d_%H-%M-%S'
    profile: sbc
    stdout: |
      2026-08-11_21-30-00
    exit: 0""")

    # 2) netconfprov as root: the real node refuses (see KKP16_execution.log),
    #    which drives the workflow onto its netconfcli fallback.
    rules.append("""  - match: 'netconfprov .*--user root'
    profile: sbc
    stdout: ''
    exit: 1""")

    # 3) netconfprov as netconfcli: succeeds silently, file written
    rules.append("""  - match: 'netconfprov .*--user netconfcli'
    profile: sbc
    stdout: ''
    exit: 0""")

    # 4) reading each generated per-table XML back
    for table in TABLES:
        rules.append("  - match: 'cat /storage/%s_.*_Precheck\\.xml'\n"
                     "    profile: sbc\n"
                     "    stdout: |\n%s\n    exit: 0"
                     % (table, indent(block(table))))

    scenario = (
        "# Generated by prep_sbc33_precheck.py - do not hand-edit.\n"
        "# Node-side answers for SBC_33_LIC_LOADING_IN_SBC_PRECHECK, taken verbatim\n"
        "# from the operator's Signaling_Activity_pre_logs.xml.\n"
        "defaults:\n"
        "  shell_exit: 0\n"
        "users:\n"
        "  %s: sbc\n"
        "  installer: repo\n"
        "rules:\n" % SIM_USER
    ) + "\n".join(rules) + "\n"

    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(scenario)


def build_response_files(xml_text, run_dir):
    """Emit the same answers in the two operator-facing formats.

    answers/            one .xml per table - the reply bodies
    answers.txt         flat  'command => @file'  mapping
    answers.yaml        single file holding request + response together
    """
    ans_dir = os.path.join(run_dir, "answers")
    os.makedirs(ans_dir, exist_ok=True)

    header = re.search(r"<config\b[^>]*>", xml_text).group(0)
    for table in TABLES:
        body = extract_table(xml_text, table)
        body = "\n".join("  " + l if l.strip() else l for l in body.split("\n"))
        with open(os.path.join(ans_dir, table + ".xml"), "w",
                  encoding="utf-8", newline="\n") as fh:
            fh.write("%s\n%s\n</config>\n" % (header, body))

    txt = [
        "# SBC_33 LIC_LOADING precheck - node answers.",
        "#   <command regex>  =>  <inline reply | @file>   | options",
        "# options: exit=N, profile=NAME, occurrences=1,2",
        "",
        r"date \+%Y-%m-%d_%H-%M-%S            => 2026-08-11_21-30-00        | profile=sbc",
        "# root cannot run netconfprov on a real node - drives the netconfcli fallback",
        r"netconfprov .*--user root           =>                            | profile=sbc, exit=1",
        r"netconfprov .*--user netconfcli     =>                            | profile=sbc, exit=0",
    ]
    for table in TABLES:
        txt.append(r"cat /storage/%s_.*_Precheck\.xml => @answers/%s.xml | profile=sbc"
                   % (table, table))
    with open(os.path.join(run_dir, "answers.txt"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(txt) + "\n")

    ymls = [
        "# SBC_33 LIC_LOADING precheck - request and response in one file.",
        "profile: sbc",
        "users:",
        "  %s: sbc" % SIM_USER,
        "  installer: repo",
        "exchanges:",
        "  - request:  'date \\+%Y-%m-%d_%H-%M-%S'",
        "    response: '2026-08-11_21-30-00'",
        "",
        "  # root cannot run netconfprov on a real node - drives the netconfcli fallback",
        "  - request:  'netconfprov .*--user root'",
        "    response: ''",
        "    exit: 1",
        "",
        "  - request:  'netconfprov .*--user netconfcli'",
        "    response: ''",
        "    exit: 0",
    ]
    for table in TABLES:
        ymls += [
            "",
            "  - request:       'cat /storage/%s_.*_Precheck\\.xml'" % table,
            "    response_file: answers/%s.xml" % table,
        ]
    with open(os.path.join(run_dir, "answers.yaml"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(ymls) + "\n")


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    template, xml_path, out_root = sys.argv[1], sys.argv[2], sys.argv[3]
    run_dir = os.path.join(out_root, "run")
    os.makedirs(run_dir, exist_ok=True)

    with open(xml_path, encoding="utf-8") as fh:
        xml_text = fh.read()

    sim_tpl = os.path.join(run_dir, "SBC_33_PRECHECK_sim.yaml")
    changes = repoint_template(template, sim_tpl)
    print("template -> " + sim_tpl)
    for c in changes:
        print(c)

    scen = os.path.join(run_dir, "scenario.yaml")
    build_scenario(xml_text, scen)
    print("scenario -> " + scen)

    build_response_files(xml_text, run_dir)
    print("responses -> %s  (answers.txt, answers.yaml, answers/)" % run_dir)
    for t in TABLES:
        print("  serves <%s> (%d bytes)" % (t, len(extract_table(xml_text, t))))

    # sanity: both artefacts must parse
    try:
        import yaml
    except ImportError:
        return
    for p in (sim_tpl, scen):
        with open(p, encoding="utf-8") as fh:
            yaml.safe_load(fh)
    print("both files parse as YAML")


if __name__ == "__main__":
    main()
